In [1]:
import json

In [4]:
import json
import numpy as np
import pandas as pd

with open('../data/bonalog.json', encoding='utf-8') as file:
    nalog = json.load(file)

In [38]:
len(nalog)

2615

In [39]:
extracted_nalog = {}

for inn, sample in nalog.items():
    # print("inn", inn)
    features = {}
    # latest_year = max(sample.keys())
    # print(latest_year)
    for year in sorted(sample.keys()):
        year_data = sample[year]
        # print(year_data["financialResult"])
        # features["capital_amount"] = year_data["financialResult"]["total3100"]
        if "balance" in year_data:
            if "current1700" in year_data["balance"]:
                features["actives"] = year_data["balance"]["current1700"]
            if "current2110" in year_data["financialResult"]:
                features["revenue"] = year_data["financialResult"]["current2110"]

        if "balance" in year_data:
            if "current1500" in year_data["balance"]:
                features["short_term_debt"] = year_data["balance"]["current1500"]
            
            if "current1400" in year_data["balance"]:
                features["long_term_debt"] = year_data["balance"]["current1400"]
    extracted_nalog[inn] = features

In [40]:
len(extracted_nalog)

2615

In [41]:
for inn, features in extracted_nalog.items():
    if len(features) == 0:
        print(inn)
        break

7719661595

In [ ]:
next(iter(extracted_nalog.values()))

{'actives': 26011.0,
 'revenue': 43153.0,
 'short_term_debt': 27021.0,
 'long_term_debt': 70.0}

In [27]:
nalog["7811533500"]["2020"]

{'id': 9849802,
 'balance': {'id': 9849802,
  'okud': '0710001',
  'expl1110': '',
  'current1110': None,
  'previous1110': None,
  'beforePrevious1110': None,
  'expl1120': '',
  'current1120': None,
  'previous1120': None,
  'beforePrevious1120': None,
  'expl1130': '',
  'current1130': None,
  'previous1130': None,
  'beforePrevious1130': None,
  'expl1140': '',
  'current1140': None,
  'previous1140': None,
  'beforePrevious1140': None,
  'expl1150': '',
  'current1150': 166.0,
  'previous1150': 401.0,
  'beforePrevious1150': 979.0,
  'expl1160': '',
  'current1160': None,
  'previous1160': None,
  'beforePrevious1160': None,
  'expl1170': '',
  'current1170': None,
  'previous1170': None,
  'beforePrevious1170': None,
  'expl1180': '',
  'current1180': 227.0,
  'previous1180': 688.0,
  'beforePrevious1180': None,
  'expl1190': '',
  'current1190': None,
  'previous1190': None,
  'beforePrevious1190': None,
  'expl1100': '',
  'current1100': 393.0,
  'previous1100': 1089.0,
  'beforePrevious1100': 979.0,
  'expl1210': '',
  'current1210': 11268.0,
  'previous1210': 9465.0,
  'beforePrevious1210': 9566.0,
  'expl1220': '',
  'current1220': 0.0,
  'previous1220': None,
  'beforePrevious1220': 46.0,
  'expl1230': '',
  'current1230': 14343.0,
  'previous1230': 7812.0,
  'beforePrevious1230': 10207.0,
  'expl1240': '',
  'current1240': None,
  'previous1240': None,
  'beforePrevious1240': None,
  'expl1250': '',
  'current1250': 8.0,
  'previous1250': 7.0,
  'beforePrevious1250': 372.0,
  'expl1260': '',
  'current1260': 0.0,
  'previous1260': None,
  'beforePrevious1260': 33.0,
  'expl1200': '',
  'current1200': 25618.0,
  'previous1200': 17284.0,
  'beforePrevious1200': 20224.0,
  'expl1310': '',
  'current1310': 15.0,
  'previous1310': 15.0,
  'beforePrevious1310': 15.0,
  'expl1320': '',
  'current1320': None,
  'previous1320': None,
  'beforePrevious1320': None,
  'expl1340': '',
  'current1340': None,
  'previous1340': None,
  'beforePrevious1340': None,
  'expl1350': '',
  'current1350': None,
  'previous1350': None,
  'beforePrevious1350': None,
  'expl1360': '',
  'current1360': None,
  'previous1360': None,
  'beforePrevious1360': None,
  'expl1370': '',
  'current1370': -1096.0,
  'previous1370': 813.0,
  'beforePrevious1370': 6540.0,
  'expl1300': '',
  'current1300': -1081.0,
  'previous1300': 828.0,
  'beforePrevious1300': 6555.0,
  'expl13101': '',
  'current13101': None,
  'previous13101': None,
  'beforePrevious13101': None,
  'expl13201': '',
  'current13201': None,
  'previous13201': None,
  'beforePrevious13201': None,
  'expl13501': '',
  'current13501': None,
  'previous13501': None,
  'beforePrevious13501': None,
  'expl13601': '',
  'current13601': None,
  'previous13601': None,
  'beforePrevious13601': None,
  'expl13701': '',
  'current13701': None,
  'previous13701': None,
  'beforePrevious13701': None,
  'expl13001': '',
  'current13001': None,
  'previous13001': None,
  'beforePrevious13001': None,
  'expl1410': '',
  'current1410': 0.0,
  'previous1410': None,
  'beforePrevious1410': 66.0,
  'expl1420': '',
  'current1420': 70.0,
  'previous1420': 125.0,
  'beforePrevious1420': 139.0,
  'expl1430': '',
  'current1430': None,
  'previous1430': None,
  'beforePrevious1430': None,
  'expl1450': '',
  'current1450': None,
  'previous1450': None,
  'beforePrevious1450': None,
  'expl1400': '',
  'current1400': 70.0,
  'previous1400': 125.0,
  'beforePrevious1400': 205.0,
  'expl1510': '',
  'current1510': 0.0,
  'previous1510': None,
  'beforePrevious1510': 23.0,
  'expl1520': '',
  'current1520': 27021.0,
  'previous1520': 17420.0,
  'beforePrevious1520': 14420.0,
  'expl1530': '',
  'current1530': None,
  'previous1530': None,
  'beforePrevious1530': None,
  'expl1540': '',
  'current1540': None,
  'previous1540': None,
  'beforePrevious1540': None,
  'expl1550': '',
  'current1550': None,
  'previous1550': None,
  'beforePrevious1550': None,
  'expl1500': '',
  'current1500': 27021.0,
  'previous1500': 17420.0,
  'beforePrevious1500': 14443.0,
  'expl1600': '',
  'current1600': 26011.0,
  'previous1600': 18373.0,
  'beforePrevious1600': 21203.0,
  'expl1700': '',
  'current1700': 26011.0,
  'previous1700': 18373.0,
  'beforePrevious1700': 21203.0},
 'financialResult': {'id': 9849802,
  'okud': '0710002',
  'expl2210': '',
  'current2210': 10.0,
  'expl2220': '',
  'current2220': 15170.0,
  'previous2220': 11094.0,
  'expl2200': '',
  'current2200': -2221.0,
  'previous2200': -4590.0,
  'expl2310': '',
  'expl2320': '',
  'expl2330': '',
  'expl2340': '',
  'current2340': 2153.0,
  'previous2340': 2367.0,
  'expl2350': '',
  'current2350': 1435.0,
  'previous2350': 4207.0,
  'expl2300': '',
  'current2300': -1503.0,
  'previous2300': -6430.0,
  'expl2410': '',
  'current2410': -406.0,
  'previous2410': 702.0,
  'expl2421': '',
  'expl2430': '',
  'expl2450': '',
  'expl2400': '',
  'current2400': -1909.0,
  'previous2400': -5728.0,
  'expl2411': '',
  'expl2412': '',
  'current2412': -406.0,
  'previous2412': 702.0,
  'expl2460': '',
  'expl2510': '',
  'expl2520': '',
  'expl2530': '',
  'expl2500': '',
  'current2500': -1909.0,
  'previous2500': -5728.0,
  'expl2900': '',
  'expl2910': '',
  'expl2110': '',
  'current2110': 43153.0,
  'previous2110': 29203.0,
  'expl2120': '',
  'current2120': 30194.0,
  'previous2120': 22699.0,
  'expl2100': '',
  'current2100': 12959.0,
  'previous2100': 6504.0},
 'capitalChange': {'id': 9849802,
  'okud': '0710004',
  'authorized3100': 15.0,
  'unallocated3100': 6540.0,
  'total3100': 6555.0,
  'authorized3220': 0.0,
  'unallocated3220': 5727.0,
  'total3220': 5727.0,
  'unallocated3221': 5727.0,
  'total3221': 5727.0,
  'authorized3200': 15.0,
  'unallocated3200': 813.0,
  'total3200': 828.0,
  'authorized3320': 0.0,
  'unallocated3320': 1909.0,
  'total3320': 1909.0,
  'unallocated3321': 1909.0,
  'total3321': 1909.0,
  'authorized3300': 15.0,
  'unallocated3300': -1096.0,
  'total3300': -1081.0,
  'beforePrevious3400': 6555.0,
  'netProfitLoss3400': -5727.0,
  'otherFactors3400': 0.0,
  'previous3400': 828.0,
  'beforePrevious3500': 6555.0,
  'netProfitLoss3500': -5727.0,
  'otherFactors3500': 0.0,
  'previous3500': 828.0,
  'beforePrevious3401': 6540.0,
  'netProfitLoss3401': -5727.0,
  'otherFactors3401': 0.0,
  'previous3401': 813.0,
  'beforePrevious3501': 6540.0,
  'netProfitLoss3501': -5727.0,
  'otherFactors3501': 0.0,
  'previous3501': 813.0,
  'current3600': -1081.0,
  'previous3600': 827.0,
  'beforePrevious3600': 6555.0},
 'fundsMovement': {'id': 9849802,
  'okud': '0710005',
  'current4110': 35640.0,
  'previous4110': 30390.0,
  'current4111': 33771.0,
  'previous4111': 29637.0,
  'current4119': 1869.0,
  'previous4119': 753.0,
  'current4120': 35639.0,
  'previous4120': 30755.0,
  'current4121': 26497.0,
  'previous4121': 22584.0,
  'current4122': 8547.0,
  'previous4122': 7154.0,
  'current4129': 595.0,
  'previous4129': 1017.0,
  'current4100': 1.0,
  'previous4100': -365.0,
  'current4400': 1.0,
  'previous4400': -365.0,
  'current4450': 7.0,
  'previous4450': 372.0,
  'current4500': 8.0,
  'previous4500': 7.0},
 'targetedFundsUsing': {'id': 9849802,
  'okud': '0710003',
  'expl6100': '',
  'current6100': 0.0,
  'expl6210': '',
  'expl6215': '',
  'expl6220': '',
  'expl6230': '',
  'expl6240': '',
  'expl6250': '',
  'expl6200': '',
  'expl6310': '',
  'expl6311': '',
  'expl6312': '',
  'expl6313': '',
  'expl6320': '',
  'expl6321': '',
  'expl6322': '',
  'expl6323': '',
  'expl6324': '',
  'expl6325': '',
  'expl6326': '',
  'expl6330': '',
  'expl6350': '',
  'expl6300': '',
  'expl6400': '',
  'current6400': 0.0},
 'simplified': False,
 'correctionVersion': 0,
 'lastCorrection': 1,
 'requiredAudit': 0,
 'auditInn': '',
 'auditName': '',
 'auditOgrn': '',
 'errorsCount': 0,
 'resultCheckCs': [],
 'datePresent': '2021-03-23',
 'prBn': 0,
 'knd': '0710099'}

## Берём
### financialResult
1. выручка (2110)

In [12]:
next(iter(nalog.keys()))

'7811533500'

In [14]:
next(iter(nalog.values()))["2020"]["balance"]

{'id': 9849802,
 'okud': '0710001',
 'expl1110': '',
 'current1110': None,
 'previous1110': None,
 'beforePrevious1110': None,
 'expl1120': '',
 'current1120': None,
 'previous1120': None,
 'beforePrevious1120': None,
 'expl1130': '',
 'current1130': None,
 'previous1130': None,
 'beforePrevious1130': None,
 'expl1140': '',
 'current1140': None,
 'previous1140': None,
 'beforePrevious1140': None,
 'expl1150': '',
 'current1150': 166.0,
 'previous1150': 401.0,
 'beforePrevious1150': 979.0,
 'expl1160': '',
 'current1160': None,
 'previous1160': None,
 'beforePrevious1160': None,
 'expl1170': '',
 'current1170': None,
 'previous1170': None,
 'beforePrevious1170': None,
 'expl1180': '',
 'current1180': 227.0,
 'previous1180': 688.0,
 'beforePrevious1180': None,
 'expl1190': '',
 'current1190': None,
 'previous1190': None,
 'beforePrevious1190': None,
 'expl1100': '',
 'current1100': 393.0,
 'previous1100': 1089.0,
 'beforePrevious1100': 979.0,
 'expl1210': '',
 'current1210': 11268.0,
 'previous1210': 9465.0,
 'beforePrevious1210': 9566.0,
 'expl1220': '',
 'current1220': 0.0,
 'previous1220': None,
 'beforePrevious1220': 46.0,
 'expl1230': '',
 'current1230': 14343.0,
 'previous1230': 7812.0,
 'beforePrevious1230': 10207.0,
 'expl1240': '',
 'current1240': None,
 'previous1240': None,
 'beforePrevious1240': None,
 'expl1250': '',
 'current1250': 8.0,
 'previous1250': 7.0,
 'beforePrevious1250': 372.0,
 'expl1260': '',
 'current1260': 0.0,
 'previous1260': None,
 'beforePrevious1260': 33.0,
 'expl1200': '',
 'current1200': 25618.0,
 'previous1200': 17284.0,
 'beforePrevious1200': 20224.0,
 'expl1310': '',
 'current1310': 15.0,
 'previous1310': 15.0,
 'beforePrevious1310': 15.0,
 'expl1320': '',
 'current1320': None,
 'previous1320': None,
 'beforePrevious1320': None,
 'expl1340': '',
 'current1340': None,
 'previous1340': None,
 'beforePrevious1340': None,
 'expl1350': '',
 'current1350': None,
 'previous1350': None,
 'beforePrevious1350': None,
 'expl1360': '',
 'current1360': None,
 'previous1360': None,
 'beforePrevious1360': None,
 'expl1370': '',
 'current1370': -1096.0,
 'previous1370': 813.0,
 'beforePrevious1370': 6540.0,
 'expl1300': '',
 'current1300': -1081.0,
 'previous1300': 828.0,
 'beforePrevious1300': 6555.0,
 'expl13101': '',
 'current13101': None,
 'previous13101': None,
 'beforePrevious13101': None,
 'expl13201': '',
 'current13201': None,
 'previous13201': None,
 'beforePrevious13201': None,
 'expl13501': '',
 'current13501': None,
 'previous13501': None,
 'beforePrevious13501': None,
 'expl13601': '',
 'current13601': None,
 'previous13601': None,
 'beforePrevious13601': None,
 'expl13701': '',
 'current13701': None,
 'previous13701': None,
 'beforePrevious13701': None,
 'expl13001': '',
 'current13001': None,
 'previous13001': None,
 'beforePrevious13001': None,
 'expl1410': '',
 'current1410': 0.0,
 'previous1410': None,
 'beforePrevious1410': 66.0,
 'expl1420': '',
 'current1420': 70.0,
 'previous1420': 125.0,
 'beforePrevious1420': 139.0,
 'expl1430': '',
 'current1430': None,
 'previous1430': None,
 'beforePrevious1430': None,
 'expl1450': '',
 'current1450': None,
 'previous1450': None,
 'beforePrevious1450': None,
 'expl1400': '',
 'current1400': 70.0,
 'previous1400': 125.0,
 'beforePrevious1400': 205.0,
 'expl1510': '',
 'current1510': 0.0,
 'previous1510': None,
 'beforePrevious1510': 23.0,
 'expl1520': '',
 'current1520': 27021.0,
 'previous1520': 17420.0,
 'beforePrevious1520': 14420.0,
 'expl1530': '',
 'current1530': None,
 'previous1530': None,
 'beforePrevious1530': None,
 'expl1540': '',
 'current1540': None,
 'previous1540': None,
 'beforePrevious1540': None,
 'expl1550': '',
 'current1550': None,
 'previous1550': None,
 'beforePrevious1550': None,
 'expl1500': '',
 'current1500': 27021.0,
 'previous1500': 17420.0,
 'beforePrevious1500': 14443.0,
 'expl1600': '',
 'current1600': 26011.0,
 'previous1600': 18373.0,
 'beforePrevious1600': 21203.0,
 'expl1700': '',
 'current1700': 26011.0,
 'previous1700': 18373.0,
 'beforePrevious1700': 21203.0}

In [5]:
nalog_df = pd.DataFrame(nalog)
nalog_df = nalog_df.transpose()
nalog_df = nalog_df.reset_index(level=0)
nalog_df.rename(columns = {'index': 'INN'}, inplace=True)
nalog_df

,INN,2019,2020,2021
0,7811533500,"{'id': 2952752, 'balance': {'id': 2952752, 'ok...","{'id': 9849802, 'balance': {'id': 9849802, 'ok...",NaN
1,1650259228,"{'id': 1590602, 'balance': {'id': 1590602, 'ok...","{'id': 9105116, 'balance': {'id': 9105116, 'ok...",NaN
2,1650264267,"{'id': 4459249, 'balance': {'id': 4459249, 'ok...","{'id': 10254239, 'balance': {'id': 10254239, '...",NaN
3,1832106240,"{'id': 2447088, 'balance': {'id': 2447088, 'ok...","{'id': 8807281, 'balance': {'id': 8807281, 'ok...","{'id': 40761702, 'balance': {'id': 40761702, '..."
4,2901238436,"{'id': 4590685, 'balance': {'id': 4590685, 'ok...","{'id': 9762679, 'balance': {'id': 9762679, 'ok...","{'id': 40763357, 'balance': {'id': 40763357, '..."
...,...,...,...,...
2610,7415101591,"{'id': 7543916, 'balance': {'id': 7543916, 'ok...","{'id': 10782264, 'balance': {'id': 10782264, '...",NaN
2611,5027271631,"{'id': 3130117, 'balance': {'id': 3130117, 'ok...","{'id': 10776365, 'balance': {'id': 10776365, '...",NaN
2612,9109023041,"{'id': 1094984, 'balance': {'id': 1094984, 'ok...","{'id': 9851710, 'balance': {'id': 9851710, 'ok...",NaN
2613,3525442903,"{'id': 4005676, 'balance': {'id': 4005676, 'ok...","{'id': 11775030, 'balance': {'id': 11775030, '...",NaN
2614,7811734020,"{'id': 2367469, 'balance': {'id': 2367469, 'ok...","{'id': 10727120, 'balance': {'id': 10727120, '...","{'id': 40564869, 'balance': {'id': 40564869, '..."